name: Build and Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build release
        run: swift build -c release

      - name: Install create-dmg
        run: |
          if ! command -v create-dmg &> /dev/null; then
            brew install create-dmg
          fi

      - name: Create DMG
        run: |
          chmod +x build-dmg.sh
          ./build-dmg.sh

      # dmg to latest release
      - name: Create or Update the latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # create the realeased tag 'latest'
          # --overwrite the existing releases
          # --generate-notes automatically adds your commit history to the release notes.
          gh release create latest Clippy-*.dmg \
          --title "Latest Build" \
          --notes "Auto-generated build from main branch." \
          --generate-notes \
          --overwrite

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: Clippy-DMG
          path: Clippy-*.dmg
          retention-days: 7
